<?php
use Zend\Form\Element\Textarea;

echo $this->blockAttachmentsForm($block);
?>
<h4>Title</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title')); ?>" name="o:block[__blockIndex__][o:data][title]">
  </div>
</div>

<h4>Text</h4>
<?php
  $textarea = new Textarea("o:block[__blockIndex__][o:data][text]");
  $textarea->setAttribute('class', 'block-html full wysiwyg');
  if ($block) {
      $textarea->setAttribute('value', $block->dataValue('text'));
  }
?>
<?php echo $this->formRow($textarea);?>

<div class="field">
  <div class="field-meta">
      <label>Link</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link')) ?>" name="o:block[__blockIndex__][o:data][link]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Link label</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('label')) ?>" name="o:block[__blockIndex__][o:data][label]">
  </div>
</div>
<?php if(isset($block)):
  $reverse = $block->dataValue('reverse');
else:
  $reverse = 0;
endif;?>
<div class="field">
  <div class="field-meta">
      <label>Reverse</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Move text to the left and image to the right (with green overlay)</div>
      </div>
  </div>
  <div class="inputs">
      <input type="checkbox" class="" value="reverse" <?php echo ($reverse == 'reverse' ? 'checked' : '') ?> name="o:block[__blockIndex__][o:data][reverse]">
  </div>
</div>
<?php if(isset($block)):
  $itemurl = $block->dataValue('itemurl');
else:
  $itemurl = '';
endif;?>
<div class="field">
  <div class="field-meta">
      <label>Link image to item?</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Add a link to the item related to the image/attachment</div>
      </div>
  </div>
  <div class="inputs">
      <input type="checkbox" class="" value="itemurl" <?php echo ($itemurl == 'itemurl' ? 'checked' : '') ?> name="o:block[__blockIndex__][o:data][itemurl]">
  </div>
</div>
<?php if(isset($block)):
  $highlight = $block->dataValue('highlight');
else:
  $highlight = 0;
endif;?>
<div class="field">
  <div class="field-meta">
      <label>Highlight text</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Make the text field more eye catching</div>
      </div>
  </div>
  <div class="inputs">
      <input type="checkbox" class="" value="highlight" <?php echo ($highlight == 'highlight' ? 'checked' : '') ?> name="o:block[__blockIndex__][o:data][highlight]">
  </div>
</div>
<?php if(isset($block)):
  $span = $block->dataValue('layout');
else:
  $span = "is-6";
endif;?>

<div class="field">
  <div class="field-meta">
      <label>Width of the text</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">12 equals full width</div>
      </div>
  </div>
  <div class="inputs">
      <select type="text" class="" name="o:block[__blockIndex__][o:data][layout]">
        <option <?php echo $span == "is-6" ? 'selected' : "";?> value="is-6">text 1/2, image 1/2</option>
        <option <?php echo $span == "is-8" ? 'selected' : "";?> value="is-8">text 2/3, image 1/3</option>
      </select>
  </div>
</div>