<?php if($block->dataValue('text')):?>
<div class="section text-only">
<?php else:?>
<div class="section" style="padding-bottom:2rem;">
<?php endif?>
    <div class="container">
      <?php if($block->dataValue('title')):?>
        <h2 class="title is-3"><?php echo $block->dataValue('title');?></h2>
      <?php endif;?>
      <?php if($block->dataValue('text') && !$block->dataValue('text2')):?>
        <div class="columns is-gapless">
          <div class="column is-12">
            <div class="content">
              <?php echo $block->dataValue('text');?>
            </div>
          </div>
        </div>
      <?php endif;?>
      <?php if($block->dataValue('text') && $block->dataValue('text2')):?>
        <div class="columns">
          <div class="column">
            <div class="content">
            <?php echo $block->dataValue('text');?>
            </div>
          </div>
          <div class="column">
            <div class="content">
            <?php echo $block->dataValue('text2');?>
            </div>
          </div>
        </div>
      <?php endif;?>
    </div>
</div>
