<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
$this->htmlElement('body')->appendAttribute('class', 'index search');
?>

<section class="section breadcrumb-section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="/">Home</a></li>
        <li>Zoekresultaten</li>
      </ul>
    </nav>
  </div>
</section>
<section class="section">
  <div class="container">
    <h1 class="title is-2 is-family-secondary"><?php echo sprintf($this->translate('Search results for “%s”'), $query); ?></h1>
    
    <?php if (empty($results)): ?>
        <p><?php echo $translate('No result found'); ?></p>
    <?php else: ?>
      <?php
        $resourceLabels = [
            'site_pages' => 'Site pages', // @translate
            'items' => 'Items', // @translate
            'item_sets' => 'Item sets', // @translate
            'media' => 'Media', // @translate
        ];
        $resourceControllers = [
            'site_pages' => 'page',
            'items' => 'item',
            'item_sets' => 'item-set',
            'media' => 'media',
        ];
      ?>
      
      <?php foreach ($results as $resourceName => $result): ?>
        <div class="content">
        <div class="<?php echo $resourceName; ?> results">
            <h2><?php echo $translate($resourceLabels[$resourceName]); ?></h2>

                <?php $titleMethod = $resourceName === 'site_pages' ? 'title' : 'displayTitle'; ?>
            <ul>
                <?php foreach ($result['resources'] as $resource): ?>
                <li>
                    <?php echo $resource->link($resource->$titleMethod()); ?>
                </li>
                <?php endforeach; ?>
            </ul>
                <?php echo $hyperlink(
                    sprintf($translate('View all results (%s total)'), $result['total']),
                    $url(
                        'site/resource',
                        ['controller' => $resourceControllers[$resourceName], 'action' => 'browse'],
                        ['query' => ['fulltext_search' => $query]],
                        true
                    )
                ); ?>
        </div>
        </div>
      <?php endforeach; ?>
      <?php endif;?>
      
    </div>  
</section>