<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var string $value
 * @var string $label
 * @var int $count
 * @var bool $active
 * @var string $url
 * @var \Zend\View\Helper\EscapeHtml $escapeHtml
 */


$escapedValue = $escapeHtmlAttr($value);
$escapedId = $name . '[]' . $escapedValue;
$displayCount = !empty($options['display_count']);
?>

<input type="checkbox" name="facet[<?= $name ?>][]" id="<?= $escapedId ?>" value="<?= $escapedValue ?>" data-url="<?= $escapeHtmlAttr($url) ?>" <?php if ($active) echo ' checked="checked"'; ?>/>
<label for="<?= $escapedId ?>"><?= $escapeHtml($label) ?><?php if ($displayCount): ?> (<span class="count"><?= $count ?></span>)<?php endif; ?></label>