<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var array $facetValues With value, count, active, label and url when needed.
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$displayCount = !empty($options['display_count']);
$URI = "$_SERVER[REQUEST_URI]";
$URI = explode("/",$URI);
$lang = strip_tags($URI[2]);
?>

<?php    
    if($name == "item_set_id_is"):
        $sort_r = [];
        foreach ($facetValues as $k=>$facetValue):
            $item_set = $this->api()->read('item_sets', $facetValue['value']);
            $item_set = $item_set->getContent();
            $sort_r[$item_set->value('dcterms:title', array('lang' => $lang)).''] = $facetValue;        
        endforeach;
        ksort($sort_r);
        $facetValues = $sort_r;
    endif;
?> 

<ul class="search-facet-items">
    <?php if(sizeof($facetValues) > 10):?>
        <input class="form-control txtSearch" type="text" placeholder="filter">
    <?php endif;?>
    <?php foreach ($facetValues as $key => $facetValue): ?>
        <li class="search-facet-item">
            <span class="<?= $facetValue['active'] ? 'active' : 'inactive' ?>">
                <?php if($name != "item_set_id_is"):?>
                    <div class="facet-link" data-facet-link="<?= $escapeAttr($facetValue['url']) ?>" onclick="activeLink(event)"><?= $escape($facetValue['label']) ?>
                <?php else:?>
                    <div class="facet-link" data-facet-link="<?= $escapeAttr($facetValue['url']) ?>" onclick="activeLink(event)"><?= $escape($key) ?>
                <?php endif;?>      
                <?php if ($displayCount): ?>
                <span class="count">(<?= $facetValue['count'] ?>)</span></div>
                <?php endif; ?>
            </span>
        </li>
    <?php endforeach; ?>
</ul>
