<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var string $value
 * @var string $label
 * @var int $count
 * @var bool $active
 * @var string $url
 * @var \Zend\View\Helper\EscapeHtml $escapeHtml
 */
$displayCount = !empty($options['display_count']);
?>

<span class="<?= $active ? 'active' : 'inactive' ?>">
    <?php 
    if($facetLabel($name) == 'Datering'):
        $datum = explode(' / ',$label);
        if(isset($datum[1])):
            if($datum[1] != $datum[0]):
                $label = $datum[0].' - '.$datum[1];
            else:
                $label = $datum[0];   
            endif;
        else:
            $label = $datum[0];    
        endif;  
    endif;    
    ?>    
    <a href="<?= $escapeHtml($url) ?>"><?= $escapeHtml($label) ?></a>

    <?php if ($displayCount): ?>
    (<span class="count"><?= $count ?></span>)
    <?php endif; ?>
</span>
