<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var string $value
 * @var string $label
 * @var int $count
 * @var bool $active
 * @var string $url
 * @var array $options
 * @var \Laminas\View\Helper\EscapeHtml $escapeHtml
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeHtmlAttr
 * @var \Laminas\View\Helper\TranslatorAwareTrait $translate
 * @var \Search\View\Helper\FacetLabel $facetLabel
 */

// Warning: when inactive, don't return anything, in particular don't return any space,
// else it should be managed in facets.phtml.

if (!$active) return;
?>

<a class="button is-text is-small facet-active" href="<?= $escapeHtmlAttr($url) ?>" data-facet-name="facet[<?= $escapeHtmlAttr($name) ?>][]" data-facet-value="<?= $escapeHtmlAttr($value) ?>"><span style="color:#666;padding:0px 3px;font-weight:bold">x</span><?= $escapeHtml(sprintf('%s : %s', $translate($facetLabel($name)), $label)) ?></a>