<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var string $tag
 */

$hyperlink = $this->plugin('hyperlink');
$lang = $site->slug();
?>

  <div class="grid-item">
    <a class="grid-link-wrapper" href="<?php echo $resource->url();?>">
      <div class="resource-thumbnail">
          <?php $media = $resource->primaryMedia(); ?>
          <?php if ($media): ?>
              <?= $this->thumbnail($media, 'medium', ['title' => $resource->displayTitle(), 'alt' => $resource->displayTitle()]) ?>
          <?php endif; ?>
      </div>
      <div class="resource-metadata">
          <h4 class="title is-6 is-family-secondary"><span><?= $resource->value('dcterms:title', array('lang' => $lang)) ?></span></h4>
          <?php 
            $body = $resource->value('dcterms:description', array('lang' => $lang));
            if(!$body){
              $body = $resource->value('dcterms:description');
            }
          ?>
          
          <?php if ($body): ?>
              <div class="description">
                <?php if ($body): ?>
                  <p>
                    <?php $trunc = implode(" ", array_slice(explode(" ", $body), 0, 16)); ?>
                    <?php if(strlen($body) != strlen($trunc)):?>
                      <?php echo $trunc.' ...';?>
                    <?php else:?>
                      <?php echo $trunc;?>
                    <?php endif;?>
                  </p>
                <?php endif; ?>
              </div>
          <?php endif; ?>
      </div>
    </a>
  </div>
