<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2020
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Search\Query $query
 * @var \Search\Response $response
 * @var array $sortOptions
 * @var array $facets
 * @var bool $isPartial Allow to use this partial in admin board when true.
 */
$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$translatePlural = $plugins->get('translatePlural');
$assetUrl = $plugins->get('assetUrl');
$partial = $plugins->get('partial');
$api = $plugins->get('api');
$vars = $this->vars();

$isPartial = !$site;
$skipFormAction = !empty($skipFormAction);

// Used in case of a redirect of item-set/show to search, when used like item/browse.
//$itemSetId = $this->params()->fromRoute('item-set-id');
// TODO Use site item set ?
//$itemSet = $itemSetId ? $api->searchOne('item_sets', ['id' => $itemSetId])->getContent() : null;
$itemSetId = false;
$itemSet = "";
$this->headScript()->appendFile($this->assetUrl('jquery-ui.min.js', 'jQueryUI'));
$this->headLink()->appendStylesheet($this->assetUrl('jquery-ui.min.css', 'jQueryUI'));
$this->headLink()->appendStylesheet($assetUrl('css/search.css', 'Search'));
$this->headScript()->appendFile($assetUrl('js/search.js', 'Search'), 'text/javascript', ['defer' => 'defer']);
?>
<section class="section breadcrumb-section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<?php echo $site->url();?>">Home</a></li>
        <?php if($searchPage->name() == "Objects"):?>
          <li><a href="<?php echo $site->url();?>/page/collectie">Collection</a></li>
        <?php else: ?>
          <li><a href="<?php echo $site->url();?>/page/collectie">Collectie</a></li>
        <?php endif;?>        
        <li><?php echo $searchPage->name();?></li>
      </ul>
    </nav>
  </div>
</section>
<?php if (empty($isPartial)): ?>
<section class="section">
  <div class="container" role="main">
  <?php endif; ?>

  <?php if ($itemSetId): ?>

      <?php $itemSet = $this->api()->read('item_sets', ['id' => $itemSetId])->getContent(); ?>
      <?php $this->vars()->offsetSet('itemSet', $itemSet); ?>
      <?php $this->vars()->offsetSet('resourceType', 'item_sets'); // TODO Check if really needed. ?>
      <?php $this->htmlElement('body')->appendAttribute('class', 'page search-page item-set resource browse'); ?>
      <?= $this->pageTitle($itemSet->displayTitle(), 2) ?>
      <h1 class="title is-2 is-family-secondary"><?= $translate('Item set') ?></h1>
      <div class="metadata">
          <?= $itemSet->displayValues() ?>
      </div>
      <div class="item-set-items">
          <h2 class="title is-3 is-family-secondary"><?= $translate('Items') ?></h2>
      </div>

  <?php else: ?>

      <?php $this->htmlElement('body')->appendAttribute('class', 'page search-page resource browse'); ?>
      <h1 class="title is-2 is-family-secondary"><?php echo $searchPage->name();?> (<?= $response->getTotalResults();?>)</h1>

  <?php endif; ?>
  
  <div class="content">
    <form class="has-icons-right" action="" id="search-form">
      <div class="field has-addons">
        <div class="control">
          <input class="input is-medium" type="text" name="q" id="q" placeholder="<?php echo $translate('Search'); ?>" value="<?php echo htmlspecialchars($query->getQuery());?>"   aria-label="<?php echo $translate('Search'); ?>">
          <input name="sort" type="hidden" value="<?php echo $query->getSort();?>" />
        </div>
        <div class="control">
          <a class="button is-primary is-medium">
            <span class="icon is-large">
              <i class="fas fa-search"></i>
            </span>
          </a>
        </div>
      </div>
    </form>
  </div>
</div>
</section>
<section class="section results">
  <div class="container is-fluid">
  <?php if (isset($response)): ?>
  <div class="filter-nav">
    <div class="filter-icon">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
        <path d="M3.9 54.9C10.5 40.9 24.5 32 40 32l432 0c15.5 0 29.5 8.9 36.1 22.9s4.6 30.5-5.2 42.5L320 320.9 320 448c0 12.1-6.8 23.2-17.7 28.6s-23.8 4.3-33.5-3l-64-48c-8.1-6-12.8-15.5-12.8-25.6l0-79.1L9 97.3C-.7 85.4-2.8 68.8 3.9 54.9z" fill="none" stroke="black" transform="scale(0.9) translate(25,25)"/>
      </svg>
    </div>
    <a role="button" class="close-icon">
        <span></span>
        <span></span>
    </a>
  </div>
  <div class="columns">
    <div class="column is-one-quarter facets-group">
      <aside class="facets">
      <form method="GET" id="psl-search-form">
          <div id="psl-search-form-date">
            <?php 
              $dates = $query->getDateRangeFilters();
              //var_dump($dates);
              $to = '2023';$from = '1000';
              if($dates):
                $from = $dates["dcterms_date_drm"][0]["from"];                  
                $to = $dates["dcterms_date_drm"][0]["to"];
              endif;         
              if(!$from){$from = "1000";}       
              if(!$to){$from = "2023";}   
            ?>
            <label><?php echo $this->translate('Date'); ?> 
            <span class="currentDate">
              <?php if($from && $to):?>
                <?php echo $from." - ".$to;?>
              <?php endif;?>  
            </span>
            </label>
            <?php //echo $this->formCollection($form->get('date'), false); ?>
            <div class="field" style="display: none;">
            <div class="field-meta">
                <label for="dcterms_date_drm[from]">From year</label>            </div>
            <div class="inputs">                
                <input type="text" name="dcterms_date_drm[from]" placeholder="YYYY" value="<?php echo $from;?>">    </div>
            </div>
            <div class="field" style="display: none;">
            <div class="field-meta">
                <label for="dcterms_date_drm[to]">To year</label>            </div>
            <div class="inputs">
                <input type="text" name="dcterms_date_drm[to]" placeholder="YYYY" value="<?php echo $to;?>">    </div>
            </div>
            <div id="psl-search-form-date-slider"></div>
            <div id="psl-search-form-date-graduations">
                <div><?php echo $this->translate('1000'); ?></div>
                <div><?php echo $this->translate('1250'); ?></div>
                <div><?php echo $this->translate('1500'); ?></div>
                <div><?php echo $this->translate('1750'); ?></div>
                <div><?php echo $this->translate('2023'); ?></div>
            </div>
          </div>  
          <div class="psl-tab-submit"><input type="submit" value="OK"/></div>      
        </form>
        <?= $partial('search/facets', [
          'searchPage' => $searchPage,
          'query' => $query,
          'response' => $response,
          'itemSet' => $itemSet,
          'site' => $site,
      ]) ?>
      
      </aside>
    </div>
     
      <div class="column is-three-quarter">
          <?php if ($response->getTotalResults()): ?>
              <?php $itemSetsCount = $response->getResourceTotalResults('item_sets'); ?>
              <?= $partial('search/resource-list', [
                  'site' => $site,
                  'title' => sprintf($translatePlural('%s item set', '%s item sets', $itemSetsCount), $itemSetsCount),
                  'response' => $response,
                  'resourceName' => 'item_sets',
              ]) ?>

              <?php $itemsCount = $response->getResourceTotalResults('items'); ?>
              <?= $partial('search/resource-list', [
                  'site' => $site,
                  'title' => sprintf($translatePlural('%s item', '%s items', $itemsCount), $itemsCount),
                  'response' => $response,
                  'resourceName' => 'items',
              ]) ?>

              <?= $partial('search/results-footer', [
                  'searchPage' => $searchPage,
                  'query' => $query,
                  'response' => $response,
              ]) ?>


          <?php elseif (empty($query) && empty($itemSetId)): ?>

              <div class="noresults"><?= $translate('Fill a query and get results.') ?></div>

          <?php elseif (empty($query) && $itemSetId): ?>

              <div class="noresults"><?= $translate('This item set has no items.') ?></div>

          <?php else: ?>

              <div class="noresults"><?= $translate('Your query returned no results') ?></div>

          <?php endif; ?>

      </div>


  </div>

  <?php else: ?>

  <div class="search-results-wrapper">
      <div class="search-results">
          <div class="noresults"><?= $translate('An error occured and your query returned no results.') ?></div>
      </div>
  </div>

  <?php endif; ?>

  <?php if (empty($isPartial)): ?>
  </div>
  <?php endif; ?>
  </div>
</section>
<script>
$(".facet-active").on("click touchstart", function(e) {
  e.preventDefault();
  var href = $(this).attr("href");
  localStorage.setItem('openPopUp', 'true');
  window.location.href = href;
});

function activeLink(event) {  
    event.preventDefault();
    var facetLink = event.currentTarget.dataset.facetLink;
    localStorage.setItem('openPopUp', 'true');
    console.log("test");
    //window.location.href = facetLink;
}

$(window).on('load', function() {
  var openPopUp = localStorage.getItem('openPopUp');
  var filterIcon = $(".filter-icon");
  var closeIcon = $(".close-icon");
  var page = $('.page');
  var facetsList = $('.facets').parent();

  if (window.innerWidth < 1024) {
    if (openPopUp === "true") {
        var filterNav = $(".filter-nav");
        $(facetsList).addClass("open-facets-list");
        $(filterNav).addClass("filter-nav-fixed");
        $(filterIcon).addClass("active-item");
        $(page).addClass("pageFixed");
        localStorage.removeItem('openPopUp');
    }
  }

  filterIcon.off("click", filterIconClickHandler);
  closeIcon.off("click", closeIconClickHandler);

  filterIcon.on("click", filterIconClickHandler);
  closeIcon.on("click", closeIconClickHandler);
});

function clickOnButton(facetsList, filterNav, filterIcon, page) {
  var filterOpen = $(facetsList).hasClass("open-facets-list");

  if (!filterOpen) {
      $(facetsList).addClass("open-facets-list");
      $(filterNav).addClass("filter-nav-fixed");
      $(filterIcon).addClass("active-item");
      $(page).addClass("pageFixed");
  } else {
      $(facetsList).removeClass("open-facets-list");
      $(filterNav).removeClass("filter-nav-fixed");
      $(filterIcon).removeClass("active-item");
      $(page).removeClass("pageFixed");
  }
}

function filterIconClickHandler() {
    var filterNav = $(".filter-nav");
    var filterIcon = $(".filter-icon");
    var page = $('.page');
    var facetsList = $('.facets').parent();
    clickOnButton(facetsList, filterNav, filterIcon, page);
}

function closeIconClickHandler() {
    var filterNav = $(".filter-nav");
    var filterIcon = $(".filter-icon");
    var page = $('.page');
    var facetsList = $('.facets').parent();
    clickOnButton(facetsList, filterNav, filterIcon, page);
}

$('#psl-search-form').on('submit',function(e){
  e.preventDefault();
  const params = new URLSearchParams(window.location.search)

  localStorage.setItem('openPopUp', 'true');
  
  params.set('dcterms_date_drm[from]',$('[name="dcterms_date_drm[from]"]').val());     
  params.set('dcterms_date_drm[to]',$('[name="dcterms_date_drm[to]"]').val());     
  window.location.href = location.protocol + '//' + location.host + location.pathname+'?'+params.toString();
});

$(document).ready(function() {
  var dateFrom = $('#psl-search-form input[name="dcterms_date_drm[from]"]');
  var dateTo = $('#psl-search-form input[name="dcterms_date_drm[to]"]');
  var dateMin =1000;
  var dateMax = 2023;
  var currentDate = '';
  console.log(dateFrom.val() + "," + dateTo.val());

  $('#psl-search-form-date-slider').slider({
      range: true,
      min: dateMin,
      max: dateMax,        
      step: 10,
      
      //values: [dateFrom.val() || dateMin, dateTo.val() || dateMax],
      values: [<?php echo $from;?>, <?php echo $to;?>],
      change: function(event, ui) {
          var from = ui.values[0] > dateMin ? ui.values[0] : '';
          var to = ui.values[1] < dateMax ? ui.values[1] : '';
          if (from != dateFrom.val()) {
              dateFrom.val(from).change();
          }
          if (to != dateTo.val()) {
              dateTo.val(to).change();
          }

          var fromv = from;
          if(from == 0){
            fromv = 1000;
          }
          var tov = to;
          if(to == ''){
            tov = 2023;
          }
          $('.currentDate').text((fromv) + ' - ' + tov);
      }
  });

  dateFrom.parents('.field').hide();
  dateTo.parents('.field').hide();
});
</script>