<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$lang = $site->slug();
$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$news= false;
$template_id = '';
if(isset($_GET['resource_template_id'])):
  $template_id = $_GET['resource_template_id'];
endif;
if($template_id == 2):
  $news = true;
endif;
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>
<section class="section breadcrumb-section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<?php echo $site->url();?>">Home</a></li>
        <?php if ($itemSetShow):?>
          <li><a href="<?php echo $site->url();?>/page/collectie"><?php echo $translate('Collectie'); ?></a></li>
          <li><?php echo $itemSet->displayTitle(); ?></li>
        <?php elseif ($news):?>
          <li><?php echo sprintf($this->translate('Nieuws')); ?></li>
        <?php else:?>
          <li><?php echo sprintf($this->translate('Items')); ?></li>
        <?php endif;?>
      </ul>
    </nav>
  </div>
</section>
<section class="section">
  <div class="container">
    <?php if ($itemSetShow): ?>
        <h1 class="title is-2 is-family-secondary"><?php echo $itemSet->value('dcterms:title', array('lang' => $lang)); ?></h1>
        <div class="columns">
          <?if($itemSet->value('dcterms:description', array('lang' => $lang)) || $itemSet->value('dcterms:provenance', array('lang' => $lang))):?>

            <div class="column is-8">
              <?if($itemSet->value('dcterms:description', array('lang' => $lang))):?>
              <div class="content text-box">
                <h4 class="title is-4"><?php echo $translate("Beschrijving");?></h4>
                <?php echo $itemSet->value('dcterms:description', array('lang' => $lang))->asHtml(); ?>
              </div>
              <?php endif;?>
              <?if($itemSet->value('dcterms:provenance', array('lang' => $lang))):?>
              <div class="content text-box">
                <h4 class="title is-4"><?php echo $translate("Geschiedenis");?></h4>
                <?php echo $itemSet->value('dcterms:provenance', array('lang' => $lang))->asHtml(); ?>
              </div>
              <?php endif;?>
              <div class="content text-box">
                <h4 class="title is-4"><?php echo $translate("Praktische info");?></h4>
                <div class="metadata">
                    <?php echo $itemSet->displayValues(); ?>
                </div>

              </div>
            </div>
          <?php endif;?>

          <div class="column">
            <?php
            $media = $itemSet->thumbnail();
            $mediaurl = '';
            if($media):?>
                <?php $mediaurl = str_replace('http:','',$media->assetUrl('medium'));?>
                <img src="<?php echo $mediaurl;?>" />
                <?php if($itemSet->value('dcterms:rights')):?>
                  <div class="caption">
                    <?php echo $itemSet->value('dcterms:rights')->asHtml(); ?>
                  </div>
                <?php endif;?>
            <?php endif;?>

          </div>
      </div>
      <div class="item-set-items">
    <?php elseif ($news):?>
        <h1 class="title is-2 is-family-secondary"><?php echo $translate('Nieuws'); ?></h1>
    <?php else: ?>
        <h1 class="title is-2 is-family-secondary"><?php echo $translate('Items'); ?></h1>
    <?php endif; ?>

    <?php //echo $this->searchFilters(); ?>

    <?php if(sizeof($items) > 0):?>
      <?php if (!$itemSetShow): ?>
      
      <?php endif;?>  
      <?php $this->trigger('view.browse.before'); ?>
      <div class="columns is-multiline">
        <?php
        $headingTerm = $this->siteSetting('browse_heading_property_term');
        $bodyTerm = $this->siteSetting('browse_body_property_term');
        $i=0;
        foreach ($items as $item):
            if ($itemSetShow && $i==6):
              continue;
            endif;  
            $heading = $item->value('dcterms:title', array('lang' => $lang));
            $body = $item->value('dcterms:description', array("lang" => $lang));
            $media = $item->media();
            if($media):
                $mediaurl = str_replace('http:', '', $media[0]->thumbnailUrl('medium'));
            else:
              $mediaurl = "";
            endif;
        ?>
        <?php if (!$news):?>
          <div class="column is-4">
            <div class="card equal-height">
              <a class="card-link-wrapper" href="<?php echo $item->url();?>">
                <div class="card-bg card-bg-img-2"
                  style="background:url(<?php echo  $mediaurl;?>) no-repeat center 20%;background-color:#7fb5b2;background-size: cover;"
                  >
                </div>
                <header class="card-header">
                  <p class="card-header-title title is-5 is-family-secondary">
                      <span><?php echo $heading;?></span>
                  </p>
                </header>
                <?php if ($body): ?>
                <div class="card-content">
                  <div class="content">                    
                      <p>
                        <?php $trunc = implode(" ", array_slice(explode(" ", $body), 0, 21)); ?>
                        <?php if(strlen($body) != strlen($trunc)):?>
                          <?php echo $trunc.' ...';?>
                        <?php else:?>
                          <?php echo $trunc;?>
                        <?php endif;?>
                      </p>                    
                  </div>
                </div>
                <?php endif; ?>
              </a>
            </div>
          </div>
        <?php else:?>
          <div class="column is-12">
            <div class="columns">
              <div class="column is-2">
                <?php if ($itemThumbnail = $this->thumbnail($item, 'square')): ?>
                  <?php echo $item->linkRaw($itemThumbnail); ?>
                <?php else: ?>

                <?php endif;?>
              </div>
              <div class="column is-8">
                <div class="browse-text" style="padding:1.5rem">
                  <a class="card-link-wrapper" href="<?php echo $item->url();?>">
                  <h3 class="title is-5 is-family-secondary">
                      <span><?php echo $item->value('dcterms:title'); ?></span>
                  </h3>
                  <div class="content">
                    <?php $date =  $item->value('dcterms:date');?>
                    <?php if($date):?>
                      <?php $date = new DateTime($date->asHtml());?>
                      <div style="margin-bottom:0.3rem;color:#666;">
                        <?php echo $date->format('d-m-Y');?>
                      </div>            
                    <?php endif;?> 
                    <?php if ($body): ?>
                      <p>
                        <?php $trunc = implode(" ", array_slice(explode(" ", $body), 0, 31)); ?>
                        <?php if(strlen($body) != strlen($trunc)):?>
                          <?php echo $trunc.' ...';?>
                        <?php else:?>
                          <?php echo $trunc;?>
                        <?php endif;?>
                      </p>
                    <?php endif; ?>
                  </div>
                  </a>
                </div>
              </div>
            </div>
          </div>
        <?php endif;?>
        <?php $i++;?>
        <?php endforeach; ?>
      </div>
      <?php echo ($itemSetShow) ? '</div>' : ''; ?>
      <?php $this->trigger('view.browse.after'); ?>

      <?php if ($itemSetShow): ?>
        <div class="has-text-right">
          <?php if($lang == "en"):?>
            <a href="<?php echo 'https://blendeff.be/s/'.$lang.'/objects?q=&facet[item_set_id][0]='.$itemSet->id();?>" class="button is-primary">
          
          <? else:?>
            <a href="<?php echo 'https://blendeff.be/s/'.$lang.'/objecten?q=&facet[item_set_id][0]='.$itemSet->id();?>" class="button is-primary">
          
          <?php endif;?>  
            <span><?php echo $translate("Bekijk alle objecten uit deze collectie");?></span>
            <span class="icon is-small">
              <i class="fas fa-angle-right"></i>
            </span>
          </a>
        </div>
      <?php endif;?>
    <?php else:?>
      <?php echo $this->pagination(); ?>
    <?php endif;?>
  </div>
</section>
<script>
  $('.grid').colcade({
    columns: '.grid-col',
    items: '.grid-item'
  });
  var module = document.getElementsByClassName("truncate");
  $clamp(module, {clamp: 3});
</script>
