<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
//$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/selectize.css'));
//$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
//$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/slick.js'));
$this->headScript()->prependFile($this->assetUrl('js/clamp.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/selectize.js'));
//$this->headScript()->prependFile($this->assetUrl('js/print.min.js'));

$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();

$url = $this->serverUrl(true);
//echo 'url:'.$url;
if (strpos($url, 'page/home') !== false || $url == "http://www.blendeff.be/" || $url == "http://blendeff.be/") {
    $home = true;
}else{
  $home = false;
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <META HTTP-EQUIV="Access-Control-Allow-Origin" CONTENT="http://https://lib.is">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.6.0/css/all.min.css" integrity="sha512-ykRBEJhyZ+B/BIJcBuOyUoIxh0OfdICfHPnPfBy7eIiyJv536ojTCsgX8aqrLQ9VJZHGz4tvYyzOM0lkgmQZGw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.6.0/js/all.min.js" integrity="sha512-kWTrl8apDL/aScTYauVsRnGkZv4n7JpH03mIdTmiELoAvAT+CGmfBQx03EMkTT34f5jvyY0DRa/M/it7iecBKw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <link rel="icon" type="image/png" href="//stijl.kuleuven.be/releases/ttt/img/favicon.png" />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;500;600;700;800&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">
        <script src="https://unpkg.com/colcade@0/colcade.js"></script>
          <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-X95H7QQCZD"></script>
        <link rel="stylesheet" href="<?php echo $this->assetUrl('css/print.css');?>" media="print"><!--add bulma-print.css-->

        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-X95H7QQCZD');
        </script>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    <?php echo $userBar; ?>

    <header>
      <section class="hero is-primary is-bold" style="background:url('/themes/base/asset/img/bg.jpeg') no-repeat center center;background-size: cover;">
        <div class="hero-overlay">
          <div class="hero-head">
            <nav class="navbar" role="navigation" aria-label="main navigation">
              <div class="container">
              <div class="navbar-brand">
                <a class="navbar-item" href="<?php echo $site->url(); ?>">

                </a>
                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
              </div>
              <div class="navbar-menu">
                <div class="navbar-start">

                </div>
                <div class="navbar-end">
                  <div class="navbar-item">
                    <?php
                      echo $site->publicNav()->menu()->renderMenu(null, [
                          'maxDepth' => $this->themeSetting('nav_depth') - 1
                      ]);
                    ?>
                  </div>
                  <div class="navbar-item">
                    <div style="color:#fff;">
                      <?php $currenturl =  "https://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";?>
                      <?php if($site->slug() == "nl"):?>
                        <?php 
                        $currenturl = str_replace("objecten","objects",$currenturl);
                        $currenturl = str_replace("/nl","/en",$currenturl);
                        if($currenturl == "https://blendeff.be/"):
                          $currenturl = "https://blendeff.be/s/en";
                        endif;  
                        ?>
                        NL&nbsp;|&nbsp;<a style="font-weight:bold" href="<?php echo $currenturl;?>">EN</a>
                      <?php else:?>
                        <?php 
                        $currenturl = str_replace("objects","objecten",$currenturl);
                        $currenturl = str_replace("/en","/nl",$currenturl);
                        ?>
                        <a style="font-weight:bold" href="<?php echo $currenturl;?>">NL</a>&nbsp;|&nbsp;EN
                      <?php endif;?>  
                    </div>  
                  </div>
                  <div class="navbar-item">
                     <button class="button is-primary" id="showSearch">
                        <span class="icon is-small">
                          <i class="fas fa-search"></i>
                        </span>
                      </button>
                  </div>
                </div>
              </div>
            </div>
          </nav>

          </div>
          <div class="hero-body">
            <div class="container">
              <div class="columns">
                <div class="column is-1 logo-column">
                  <?php if ($this->themeSetting('logo')): ?>
                      <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                  <?php endif; ?>
                </div>
                <div class="column">
                  <h1 class="title is-family-secondary is-1">Blendeff</h1>
                  <?php if($site->slug() == "nl"):?>
                    <h2 class="subtitle is-family-secondary is-4">Wetenschappelijke collecties en kunstverzamelingen KU Leuven</h2>
                  <?php else:?>
                    <h2 class="subtitle is-family-secondary is-4">Scientific collections and art collections KU Leuven</h2>
                  <?php endif;?>  
                  <?php if($home):?>
                    <div class="hero-text is-size-7">
                      <div class="content">
                      <?php if($site->slug() == "nl"):?>
                        <p>
                          Van een zestiende-eeuws familieportret tot het skelet van een Groenlandse walvis. Van prehistorische schelpen tot Servranckx’ <em>Machine à émouvoir</em>. De universiteit heeft in haar lange geschiedenis een omvangrijk patrimonium aan waardevolle stukken en representatieve collecties bijeengebracht. Een academisch erfgoed dat met grote zorg en vakkundigheid wordt bewaard, voor nu en voor later.
                        </p>
                        <?php else:?>
                          <p>
                          Ranging from a 16th-century family portrait to a bowhead whale skeleton. Or from prehistoric shells to Servranckx' Machine à émouvoir. In its long history, the university has amassed a vast patrimony of valuable exhibits and representative collections. An academic heritage preserved with great care and skill, for now and later.
                        </p>
                        <?php endif;?>  
                        
                      </div>
                    </div>
                  <?php endif;?>
                </div>
              </div>
            </div>
           </div>
         </div>
      </section>

    </header>

    <div class="scroll-to-top-button">
      <svg class="svg-inline--fa fa-angle-top fa-lg" data-prefix="fas" data-icon="angle-top" role="img" viewBox="0 0 256 512" fill="none" xmlns="http://www.w3.org/2000/svg" data-fa-i2svg>
        <path fill="#ffffff" d="M201.4 137.4c12.5-12.5 32.8-12.5 45.3 0l160 160c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L224 205.3 86.6 342.6c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3l160-160z"/>
      </svg>
    </div>

    <div class="over-footer" id="printid">
      <?php echo $this->content; ?>
    </div>

    <footer class="footer">
      <div class="container">

        <nav class="level">
            <!-- Left side -->
            <div class="level-left">
              <div class="level-item">
                <div class="logos">
                  <a href="//kuleuven.be"><img alt="KU Leuven" src="<?php echo $this->assetUrl("img/kuleuven.png");?>" /></a>
                  <a href="//libis.be"><img alt="Libis" src="<?php echo $this->assetUrl("img/libis.png");?>" /></a>
                </div>
              </div>
            </div>

            <!-- Right side -->
            <div class="level-right">
              <p class="level-item">
                </p><ul>
                  <li><a href="<?php echo $site->url();?>/page/praktisch-informatie"><?php echo $translate("Gebruiksvoorwaarden");?></a></li>
                </ul><p></p>

            </div>
          </nav>
          <?php
          //get last item modified
          $item = $this->api()->searchOne('items',array("sort_by"=>"modified","sort_order"=>"desc"));
          $item = $item->getContent();          
          ?>
          <p style="font-size:0.9rem;">© KU Leuven | Last updated: <?php echo date_format($item->modified(),"d-m-Y");?></p>
      </div>
    </footer>

    <div class="search-menu modal">
      <div class="modal-background"></div>
        <div class="modal-content">
          <?php echo $this->partial('common/search-form'); ?>
        </div>
        <button class="search-menu-close modal-close is-large"></button>
     </div>

     <div class="burger-menu modal">
       <div class="modal-background"></div>
         <div class="modal-content">
           <!-- Any other Bulma elements you want -->
           <?php echo $this->partial('common/search-form'); ?>
           <?php
             echo $site->publicNav()->menu()->renderMenu(null, [
                 'maxDepth' => $this->themeSetting('nav_depth') - 1
             ]);
           ?>
           <div style="color:#fff;">
              <?php $currenturl =  "https://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";?>
              <?php if($site->slug() == "nl"):?>
                <?php 
                $currenturl = str_replace("objecten","objects",$currenturl);
                $currenturl = str_replace("/nl","/en",$currenturl);
                if($currenturl == "https://blendeff.be/"):
                  $currenturl = "https://blendeff.be/s/en";
                endif;  
                ?>
                NL&nbsp;|&nbsp;<a style="font-weight:bold" href="<?php echo $currenturl;?>">EN</a>
              <?php else:?>
                <?php 
                $currenturl = str_replace("objects","objecten",$currenturl);
                $currenturl = str_replace("/en","/nl",$currenturl);
              ?>
              <a style="font-weight:bold" href="<?php echo $currenturl;?>">NL</a>&nbsp;|&nbsp;EN
              <?php endif;?>  
            </div>  
         </div>
         <button class="burger-menu-close modal-close is-large"></button>
      </div>
  </body>
  <script>
  $(document).ready(function() {
    // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {
        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        //$(".navbar-burger").toggleClass("is-active");
        $(".burger-menu").toggleClass("is-active");
    });

    $("#showSearch").click(function() {
    $(".search-menu").addClass("is-active");
    });

    $(".search-menu-close").click(function() {
       $(".search-menu").removeClass("is-active");
    });
    $(".burger-menu-close").click(function() {
       $(".burger-menu").removeClass("is-active");
    });

    $(".scroll-to-top-button").on("click", function() {
        $("body, html").animate({ scrollTop: 0 }, 800);
    });
  });
  </script>

</html>
