<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
//$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/selectize.css'));
//$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
//$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/slick.js'));
$this->headScript()->prependFile($this->assetUrl('js/clamp.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/selectize.js'));

$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();

$url = $this->serverUrl(true);
//echo 'url:'.$url;
if (strpos($url, 'page/home') !== false || $url == "http://www.blendeff.be/" || $url == "http://blendeff.be/") {
    $home = true;
}else{
  $home = false;
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <META HTTP-EQUIV="Access-Control-Allow-Origin" CONTENT="http://https://lib.is">
        <script src="https://kit.fontawesome.com/582fb8c29f.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;500;600;700;800&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">
        <script src="https://unpkg.com/colcade@0/colcade.js"></script>
          <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-X95H7QQCZD"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-X95H7QQCZD');
        </script>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    <?php echo $userBar; ?>

    <header>
      <section class="hero is-primary is-bold" style="background:url('/themes/base/asset/img/bg.jpeg') no-repeat center center;background-size: cover;">
        <div class="hero-overlay">
          <div class="hero-head">
            <nav class="navbar" role="navigation" aria-label="main navigation">
              <div class="container">
              <div class="navbar-brand">
                <a class="navbar-item" href="<?php echo $site->url(); ?>">

                </a>
                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
              </div>
              <div class="navbar-menu">
                <div class="navbar-start">

                </div>
                <div class="navbar-end">
                  <div class="navbar-item">
                    <?php
                      echo $site->publicNav()->menu()->renderMenu(null, [
                          'maxDepth' => $this->themeSetting('nav_depth') - 1
                      ]);
                    ?>
                  </div>
                  <div class="navbar-item">
                     <button class="button is-primary" id="showSearch">
                        <span class="icon is-small">
                          <i class="fas fa-search"></i>
                        </span>
                      </button>
                  </div>
                </div>
              </div>
            </div>
          </nav>

          </div>
          <div class="hero-body">
            <div class="container">
              <div class="columns">
                <div class="column is-1 logo-column">
                  <?php if ($this->themeSetting('logo')): ?>
                      <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                  <?php endif; ?>
                </div>
                <div class="column">
                  <h1 class="title is-family-secondary is-1">Blendeff</h1>
                  <h2 class="subtitle is-family-secondary is-4">Wetenschappelijke collecties en kunstverzamelingen KU Leuven</h2>
                  <?php if($home):?>
                    <div class="hero-text is-size-7">
                      <div class="content">
                        <p>
                          Van een zestiende-eeuws familieportret tot het skelet van een Groenlandse walvis. Van prehistorische schelpen tot Servranckx’ <em>Machine à émouvoir</em>. De universiteit heeft in haar lange geschiedenis een omvangrijk patrimonium aan waardevolle stukken en representatieve collecties bijeengebracht. Een academisch erfgoed dat met grote zorg en vakkundigheid wordt bewaard, voor nu en voor later.
                        </p>
                      </div>
                    </div>
                  <?php endif;?>
                </div>
              </div>
            </div>
           </div>
         </div>
      </section>

    </header>

    <div class="over-footer">
      <?php echo $this->content; ?>
    </div>

    <footer class="footer">
      <div class="container">

        <nav class="level">
            <!-- Left side -->
            <div class="level-left">
              <div class="level-item">
                <div class="logos">
                  <a href="//kuleuven.be"><img alt="KU Leuven" src="<?php echo $this->assetUrl("img/kuleuven.png");?>" /></a>
                  <a href="//libis.be"><img alt="Libis" src="<?php echo $this->assetUrl("img/libis.png");?>" /></a>
                </div>
              </div>
            </div>

            <!-- Right side -->
            <div class="level-right">
              <p class="level-item">
                </p><ul>
                  <li><a href="<?php echo $site->url()?>/page/praktisch-informatie">Gebruiksvoorwaarden</a></li>
                </ul><p></p>

            </div>
          </nav>
          <p style="font-size:0.9rem;">© KU Leuven | Last updated: 12-10-2021</p>
      </div>
    </footer>

    <div class="search-menu modal">
      <div class="modal-background"></div>
        <div class="modal-content">
          <?php echo $this->partial('common/search-form'); ?>
        </div>
        <button class="search-menu-close modal-close is-large"></button>
     </div>

     <div class="burger-menu modal">
       <div class="modal-background"></div>
         <div class="modal-content">
           <!-- Any other Bulma elements you want -->
           <?php echo $this->partial('common/search-form'); ?>
           <?php
             echo $site->publicNav()->menu()->renderMenu(null, [
                 'maxDepth' => $this->themeSetting('nav_depth') - 1
             ]);
           ?>
         </div>
         <button class="burger-menu-close modal-close is-large"></button>
      </div>
  </body>
  <script>
  $(document).ready(function() {
    // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {
        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        //$(".navbar-burger").toggleClass("is-active");
        $(".burger-menu").toggleClass("is-active");
    });

    $("#showSearch").click(function() {
    $(".search-menu").addClass("is-active");
    });

    $(".search-menu-close").click(function() {
       $(".search-menu").removeClass("is-active");
    });
    $(".burger-menu-close").click(function() {
       $(".burger-menu").removeClass("is-active");
    });
  });
  </script>

</html>
