<?php
  $escape = $this->plugin('escapeHtml');
  $url = '';
  $site = $blockAll->page()->site();
  $siteTitle = $blockAll->page()->site()->title();  
?>
<div class="jumbotron2 kuleuven-banner">
  <div class="card card-banner card-50-50-right">
    <div class="card-img-right" style="background-image: url(https://services3.libis.be/herkul/files/asset/306da97125ad4ad9e195eafb5fec7c570dc5b9a6.jpg);">&nbsp;</div>

    <div class="card-body">
      <?php if($blockAll->dataValue('sec_title')):?>
        <h2><span><?php echo $blockAll->dataValue('sec_title');?></span></h2>
      <?php endif;?>
      
      <h1><?php echo $blockAll->dataValue('title');?></h1>

      <p><?php echo $blockAll->dataValue('text');?></p>

      <p><a class="btn btn-primary" href="<?php echo $blockAll->dataValue('link');?>"> <span><?php echo $blockAll->dataValue('link_text');?></span></a></p>
    </div>
  </div>
</div>