<?php
$layouts = [];
foreach ($page->blocks() as $block) {
    if (!array_key_exists($block->layout(), $layouts)) {
        // Prepare render only once per layout type.
        $layouts[$block->layout()] = null;
        $this->blockLayout()->prepareRender($block->layout());
    }
    if($block->layout() == 'pageTitle' || $block->layout() == 'html'):
      echo '<section class="section no-section"><div class="container">';
    endif;

    if($block->layout() == 'html'):
      echo $block->dataValue('html', '');
    else:
      echo $this->blockLayout()->render($block);
    endif;
    
    if($block->layout() == 'pageTitle' || $block->layout() == 'html'):
      $credits = $this->pageMetadata('credits') ?: null;
      if ($credits):
          echo "<h3 style='subtitle is-4'>Door ".$credits."</h3>";
      endif;
      echo '</div></section>';
      
    endif;
}
