<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

    <?php
    $nav = $site->publicNav();
    $container = $nav->getContainer();
    $activePage = $nav->findActive($container);
    $type = $this->pagesMetadata('type') ?: null;
    $next = $this->pagesMetadata('next',$page) ?: null;
    $previous = $this->pagesMetadata('previous',$page) ?: null;

    if ($activePage):
      if ($activePage['depth'] !== 0): ?>
      <section class="section breadcrumb-section">
        <div class="container">
          <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
              <li><a href="<?php echo $site->url().'/page/home'?>">Home</a></li>
              <li><?php echo $nav->breadcrumbs()->setSeparator('</li><li>'); ?></li>
            </ul>
          </nav>
        </div>
      </section>
      <?php endif; ?>
    <?php endif; ?>
<!--
<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>
<?php endif; ?>-->

<?php $this->trigger('view.show.before'); ?>
<?php echo $this->content; ?>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php //echo $this->sitePagePagination(); ?>
<?php endif; ?>

<div class="has-text-centered" style="margin-bottom:2rem;">
  <?php if($previous && ($this->pageMetadata('type',$previous) == 'exhibit_page' || $this->pageMetadata('type',$previous) == 'exhibit')):?>
    <a class="button is-outlined" href="<?php echo $previous->url();?>">Vorige</a>
  <?php endif;?>
  <?php if($next  && ($this->pageMetadata('type',$next) == 'exhibit_page'|| $this->pageMetadata('type',$next) == 'exhibit')):?>
    <a class="button is-outlined" href="<?php echo $next->url();?>">Volgende</a>
  <?php endif;?>

</div>
