<div class="container container-block">
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="kul-card-image card card-secondary card-50-50">
        <a class="card-img-link" href="">
          <div class="card-img-left" style="background-image: url(https://services3.libis.be/herkul/files/asset/306da97125ad4ad9e195eafb5fec7c570dc5b9a6.jpg);">&nbsp;</div>
        </a>
        <div class="card-body">
          <h2 class="card-title"><a href="">Feature of the month</a></h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ligula dui, euismod quis cursus ac, porttitor et sapien.</p>
          <p><a class="btn btn-ghost" href="">Lees verder</a></p>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-4">
      <div class="kul-card-image card card-primary">
        <div class="card-body">
          <h2 class="card-title"><a href="">Working groups</a></h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ligula dui, euismod quis cursus ac, porttitor et sapien.</p>
          <p><a class="btn btn-ghost-inv more" href="">More working groups</a></p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-4">
      <div class="card card-gray collection card card-body card-activity card-gray ">
        <h2 >
          <a href="">
            <span>Events</span>
          </a>
        </h2>
        <ul class="activity-list">
          <li><div class="main">
            <div class="date">17-03-2022</div>
              <a href="" title="">
                Four ERC-2021 Consolidator Grants for KU Leuven researchers
              </a>
            </div>
          </li>
          <li><div class="main">
            <div class="date">17-03-2022</div>
              <a href="" title="">
                Four ERC-2021 Consolidator Grants for KU Leuven researchers
              </a>
            </div>
          </li>
          <li><div class="main">
            <div class="date">17-03-2022</div>
              <a href="" title="">
                Four ERC-2021 Consolidator Grants for KU Leuven researchers
              </a>
            </div>
          </li>
        </ul>
        <p>
          <strong>
            <a class="more" href="">More events</a>
          </strong>  
        </p>
      </div>
    </div>

    <div class="col-xs-12 col-md-4">
      <div class="kul-card-image card card-gray">
        <div class="card-body">
          <h2>News</h2>

          <ul class="activity-list">
            <li><div class="main">
              <div class="date">17-03-2022</div>
                <a href="" title="">
                  Four ERC-2021 Consolidator Grants for KU Leuven researchers
                </a>
              </div>
            </li>
            <li><div class="main">
              <div class="date">17-03-2022</div>
                <a href="" title="">
                  Four ERC-2021 Consolidator Grants for KU Leuven researchers
                </a>
              </div>
            </li>
            <li><div class="main">
              <div class="date">17-03-2022</div>
                <a href="" title="">
                  Four ERC-2021 Consolidator Grants for KU Leuven researchers
                </a>
              </div>
            </li>
          </ul>

          <p><strong><a class="more" href="">More news</a></strong></p>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-4">
      <div class="kul-card-image card card-contact">
        <div class="card-body">
          <h2>Contact Herkul</h2>

            <div class="vcard-item"><i class="material-icons vcard-icon">person</i>

            <div class="name">Herkul</div>
            </div>

            <div class="vcard-item"><i class="material-icons vcard-icon">location_on</i>

            <div class="adr">
              <span>Address</span><br>
              <span>3000 Leuven</span><br>
              <span>Belgium</span></div>
            </div>

            <div class="vcard-item">
              <i class="material-icons vcard-icon">email</i>
              <div class="mail">  
                <a href="mailto:herkul@kuleuven.be">herkul@kuleuven.be</a>
              </div>
            </div>

            <div class="vcard-item">
              <i class="material-icons vcard-icon">phone</i>
              <div class="phone">
                <a href="tel:+32 16 32 09 29">+32 16 32 09 29</a
              ></div>
            </div>

            <div class="icons" style="margin:1rem 0">
              <!-- ngIf: all.facebook != '' -->
              <a href="" target="_blank" ><i style="font-size:1.4em" class="fa fa-facebook-official fa-2x" aria-hidden="true"></i></a>
              <!-- ngIf: all.twitter != '' -->
              <a href="" target="_blank" ><i style="font-size:1.4em" class="fa fa-twitter fa-2x" aria-hidden="true"></i></a>
              <!-- ngIf: all.instagram != '' -->
              <a href="" target="_blank" ><i style="font-size:1.4em" class="fa fa-instagram fa-2x" aria-hidden="true"></i></a>
              <!-- ngIf: all.youtube != '' -->
            </div>

            <p><strong><a class="more" href="">More about Herkul</a></strong></p>
        </div>
      </div>
    </div>
  </div>
</div>
<?php if($block->dataValue('text')):?>
<div class="section text-only">
<?php else:?>
<div class="section" style="padding-bottom:2rem;">
<?php endif?>
    <div class="container" id="<?php echo $block->dataValue('title');?>">
      <?php if($block->dataValue('title')):?>
        <h2 class="title is-3"><?php echo $block->dataValue('title');?></h2>
      <?php endif;?>
      <?php if($block->dataValue('text') && !$block->dataValue('text2')):?>
        <div class="columns is-gapless">
          <div class="column is-12">
            <div class="content">
              <?php echo $block->dataValue('text');?>
            </div>
          </div>
        </div>
      <?php endif;?>
      <?php if($block->dataValue('text') && $block->dataValue('text2')):?>
        <div class="columns">
          <div class="column">
            <div class="content">
            <?php echo $block->dataValue('text');?>
            </div>
          </div>
          <div class="column">
            <div class="content">
            <?php echo $block->dataValue('text2');?>
            </div>
          </div>
        </div>
      <?php endif;?>
    </div>
</div>
