<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$not = array('Title','Description','Is Version Of','Is Part Of','Language','Provenance');
$notalt = array('Collectie ID','Referenties object','Beeld','Beeld copyright');
?>

<?php foreach ($templateProperties as $term => $property): ?>
  <?php 
    if($property->isPrivate()):
      continue;
    endif;
    $propertyData = '';
    if(isset($values[$property->property()->term()])):
      $propertyData = $values[$property->property()->term()];
    else:
      continue;
    endif;
  ?>  
  <?php if(!in_array($propertyData['property']->label(),$not) && !in_array($propertyData['alternate_label'],$notalt)):?>
  <div class="columns ">
    <div class="column is-3" style="padding-top:0.3rem;padding-bottom:0.3rem;">
      <h4 class="title is-6" style="font-size:0.9rem;">
      <?php if ($propertyData['alternate_label']): ?>
      <?php echo $escape($propertyData['alternate_label']); ?>
      <?php else: ?>
      <?php echo $escape($translate($propertyData['property']->label())); ?>
      <?php endif; ?>
      <?php if ('term' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
      <?php elseif ('vocab' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
      <?php endif; ?>
      </h4>
    </div>
    <div class="column is-7" style="padding-top:0.3rem;padding-bottom:0.3rem;">
      <div class="values" style="font-size:0.9rem;">
      <?php $i=0;?>
      <?php foreach ($propertyData['values'] as $value): ?>
          <?php
          $valueType = $value->type();
          $class = ['value'];
          if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
              $class[] = 'resource';
              $class[] = $escape($value->valueResource()->resourceName());
          } elseif ('uri' == $valueType) {
              $class[] = 'uri';
          }
          if (!$value->isPublic()) {
              $class[] = 'private';
          }
          ?>

            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>

                <?php if($propertyData['alternate_label'] == 'Thema'):?>
                  <a target="_blank" href="/nl/item-set?fulltext_search=&property[0][joiner]=and&property[0][property]=8&property[0][type]=eq&property[0][text]=<?php echo $value->asHtml(); ?>&resource_class_id[]=&resource_template_id[]=&submit=Zoeken"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['alternate_label'] == 'Referenties'):?>
                  <?php $ref_e = explode("$$",$value->__toString());?>
                  <?php if(isset($ref_e[1])):?>
                      <a target="_blank" href="<?php echo $ref_e[1]; ?>"><?php echo $ref_e[0]; ?></a>
                  <?php else:?>
                      <?php echo $ref_e[0]; ?>
                  <?php endif;?>
                <?php elseif($propertyData['alternate_label'] == 'Datering'):?>
                  <?php 
                    $datum = explode(' / ',$value->asHtml());
                    if(isset($datum[1])):
                      if($datum[1] != $datum[0]):
                        echo $datum[0].' - '.$datum[1];
                      else:
                        echo $datum[0];   
                      endif;
                    else:
                      echo $datum[0];    
                    endif;  
                  ?>
                <?php elseif($propertyData['alternate_label'] == 'Afmetingen'):?>
                  <?php 
                    $text = str_replace("()","",$value->asHtml());
                    $text = str_replace("("," (",$text);
                    $texts = explode(';',$text);
                    if(sizeof($texts) > 1):
                      echo '<i> - '.strtolower(str_replace("Note: ","",$texts[0])).'</i><br style="margin-bottom:0.5rem;">';
                      if (strpos($texts[1], ': 0') === false):
                        echo strtolower($texts[1]);   
                      endif;  
                    else:
                      if (strpos($text, 'Note') !== false):
                        echo '<i> - '.strtolower(str_replace("Note: ","",$text)).'</i>';   
                      elseif (strpos($text, ': 0') === false):
                        echo strtolower($text);   
                      endif;                        
                    endif;              
                  ?>  
                <?php elseif($propertyData['alternate_label'] == 'Materiaal'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                    <a href="<?php echo '/s/nl/objecten?q=&facet[dcterms:medium][0]='.$text[0]; ?>"><?php echo $text[0]; ?></a>
                    <a target="_blank" href="<?php echo $text[1].$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                  <?php else:?>
                    <a href="<?php echo '/s/nl/objecten?q=&facet[dcterms:medium][0]='.$value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php endif;?> 
                <?php elseif($propertyData['alternate_label'] == 'Plaats vervaardiging'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                   <?php echo $text[0]; ?>
                    <a target="_blank" href="<?php echo 'https://www.geonames.org/'.$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>   
                <?php elseif($propertyData['alternate_label'] == 'Periode'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                   <?php echo $text[0]; ?>
                    <a target="_blank" href="<?php echo $text[1].$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>
                <?php elseif($propertyData['alternate_label'] == 'Onderwerp: wie'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                   <?php echo $text[0]; ?>
                    <a target="_blank" href="<?php echo $text[1].$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>      
                <?php elseif($propertyData['alternate_label'] == 'Onderwerp: wat'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                   <?php echo $text[0]; ?>
                    <a target="_blank" href="<?php echo $text[1].$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>           
                <?php elseif($propertyData['alternate_label'] == 'Objectnaam'):?>                  
                  <a href="<?php echo '/s/nl/objecten?q=&facet['.$property->property()->term().'][0]='.$value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['alternate_label'] == 'Gerelateerde objecten'):?>
                  <?php 
                    $query = 'property[0][joiner]=and&property[0][property]=10&property[0][type]=eq&property[0][text]='.$value->asHtml().'&item_set_id[]=&site_id=';
                    parse_str($query,$query);

                    $rel = $items = $this->api()->searchOne('items',$query);
                    $rel = $rel->getContent();
                    if($rel):
                      echo '<a href="'.$rel->url().'">'.$rel->displayTitle().'</a>';
                    else:
                     echo $value->asHtml();
                    endif; 
                  ?>                   
                  <!--<a href="<?php echo '/s/nl/objecten?q=&facet['.$property->property()->term().'][0]='.$value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>-->
                <?php elseif($propertyData['alternate_label'] == 'Vervaardiger'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                    <?php 
                      $medval = $values['dcterms:creator']['values'][$i]->asHtml();
                    ?>
                    <a href="<?php echo '/s/nl/objecten?q=&facet[dcterms:creator][0]='.$medval; ?>"><?php echo $text[0]; ?></a>
                      <?php if(sizeof($text) == 3):?>
                        <a target="_blank" href="<?php echo $text[1].$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                      <?php elseif(sizeof($text) == 2  && $text[1]):?>
                        <a target="_blank" href="<?php echo $text[1]; ?>"><i class="fas fa-info-circle"></i></a>
                      <?php endif;?>  
                     <?php else:?>
                    <a href="<?php echo '/s/nl/objecten?q=&facet[dcterms:creator][0]='.$medval; ?>"><?php echo $value->asHtml(); ?></a>
                  <?php endif;?>                  
                <?php elseif (strpos($value->asHtml(), 'http') !== false):?>
                  <a target="_blank" href="<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php else:?>
                  <?php echo $value->asHtml(); ?>
                <?php endif;?>
            </div>
            <?php $i++;?>
      <?php endforeach; ?>
      </div>
    </div>
  </div>
  <?php endif;?>
<?php endforeach; ?>
