<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$not = array('Title','Description','Is Version Of','Is Part Of','Language');
$notalt = array('Collectie ID','Referenties object','Beeld','Beeld copyright','Geschiedenis');
$URI = "$_SERVER[REQUEST_URI]";
$URI = explode("/",$URI);
$lang = strip_tags($URI[2]);
if($lang == 'nl'){
  $pre = 'nl_';
}else{
  $pre = 'en_';
}
?>

<?php foreach ($templateProperties as $term => $property): ?>
  <?php 
    if($property->isPrivate()):
      continue;
    endif;
    $comment = $property->alternateComment();
    $propertyData = '';
    if(isset($values[$property->property()->term()])):
      $propertyData = $values[$property->property()->term()];
    else:
      continue;
    endif;
  ?>  
  <?php if(!in_array($propertyData['property']->label(),$not) && !in_array($propertyData['alternate_label'],$notalt)):?>
    <?php if($comment != "extra" && $comment != ""):?>
    <div class="columns is-12"> 
      <div class="column">
        <h4 class="has-text-weight-bold is-6 section-head"><?php echo $translate($comment);?></h4>
      </div>
    </div>
  <?php endif; ?>
  <div class="columns ">
    <div class="column is-4" style="padding-top:0.3rem;padding-bottom:0.3rem;">
      <h4 class="title is-6" style="font-size:0.9rem;">
      <?php if ($propertyData['alternate_label']): ?>
      <?php echo $escape($translate($propertyData['alternate_label'])); ?>
      <?php else: ?>
      <?php echo $escape($translate($propertyData['property']->label())); ?>
      <?php endif; ?>
      <?php if ('term' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
      <?php elseif ('vocab' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
      <?php endif; ?>
      </h4>
    </div>
    <div class="column is-7" style="padding-top:0.3rem;padding-bottom:0.3rem;">
      <div class="values" style="font-size:0.9rem;">
      <?php $i=0;?>
      <?php foreach ($propertyData['values'] as $value): ?>
          <?php if($value->lang() != $lang && $value->lang() != null):?>
                  <?php continue;?>
                <?php endif;?>
          <?php
          $valueType = $value->type();
          $class = ['value'];
          if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
              $class[] = 'resource';
              $class[] = $escape($value->valueResource()->resourceName());
          } elseif ('uri' == $valueType) {
              $class[] = 'uri';
          }
          if (!$value->isPublic()) {
              $class[] = 'private';
          }
          ?>

            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">   
                
                <?php
                  if($lang == "en"):
                    $search_url = "/s/en/objects";
                    $itemset_url = "/s/en";
                  else:
                    $search_url = "/s/nl/objecten";
                    $itemset_url = "/nl";
                  endif;  

                ?>  
                <?php if($propertyData['alternate_label'] == 'Thema'):?>
                  <a target="_blank" href="<?php echo $itemset_url;?>/item-set?fulltext_search=&property[0][joiner]=and&property[0][property]=8&property[0][type]=eq&property[0][text]=<?php echo $value->asHtml(); ?>&resource_class_id[]=&resource_template_id[]=&submit=Zoeken"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['alternate_label'] == 'Referenties'):?>
                  <?php $ref_e = explode("$$",$value->__toString());?>
                  <?php if(isset($ref_e[1])):?>
                      <a target="_blank" href="<?php echo $ref_e[1]; ?>"><?php echo $ref_e[0]; ?></a>
                  <?php else:?>
                      <?php echo $ref_e[0]; ?>
                  <?php endif;?>
                <?php elseif($propertyData['alternate_label'] == 'Datering'):?>
                  <?php 
                    $datum = explode(' / ',$value->asHtml());
                    if(isset($datum[1])):
                      if($datum[1] != $datum[0]):
                        echo $datum[0].' - '.$datum[1];
                      else:
                        echo $datum[0];   
                      endif;
                    else:
                      echo $datum[0];    
                    endif;  
                  ?>
                <?php elseif($propertyData['alternate_label'] == 'Afmetingen'):?>
                  <?php 
                    $text = str_replace("()","",$value->asHtml());
                    $text = str_replace("("," (",$text);
                    $texts = explode(';',$text);
                    if(sizeof($texts) > 1):
                      echo '<i> - '.strtolower(str_replace("Note: ","",$texts[0])).'</i><br style="margin-bottom:0.5rem;">';
                      if (strpos($texts[1], ': 0') === false):
                        echo strtolower($texts[1]);   
                      endif;  
                    else:
                      if (strpos($text, 'Note') !== false):
                        echo '<i> - '.strtolower(str_replace("Note: ","",$text)).'</i>';   
                      elseif (strpos($text, ': 0') === false):
                        echo strtolower($text);   
                      endif;                        
                    endif;              
                  ?>  
                <?php elseif($propertyData['alternate_label'] == 'Materiaal'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                    <?php if($text[0]):?>
                      <a href="<?php echo $search_url.'?q=&facet['.$pre.'dcterms_medium_ss][0]='.$text[0]; ?>"><?php echo $text[0]; ?></a>
                      <?php $text[1] = str_replace("vocab.getty.edu/aat/","www.getty.edu/vow/AATFullDisplay?find=&amp;logic=AND&amp;note=&amp;subjectid=",$text[1]);?>      
                      <?php if(sizeof($text) == 3):?>                        
                        <a target="_blank" href="<?php echo $text[1].$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                      <?php else:?>
                        <a target="_blank" href="<?php echo $text[1]; ?>"><i class="fas fa-info-circle"></i></a>
                      <?php endif;?> 
                    <?php endif;?> 
                  <?php else:?>
                    <a href="<?php echo $search_url.'?q=&facet['.$pre.'dcterms_medium_ss][0]='.$value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php endif;?> 
                <?php elseif($propertyData['alternate_label'] == 'Plaats vervaardiging'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                    <?php echo $text[0]; ?>
                    <?php if(trim($text[1])):?>
                      <?php $url = trim($text[1]);?>
                    <?php else:?>
                      <?php $url = "https://www.geonames.org/";?>
                    <?php endif;?>  
                    <a target="_blank" href="<?php echo $url.$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>   
                <?php elseif($propertyData['alternate_label'] == 'Licentie'):?>
                  <?php if(strpos($value->asHtml(), 'Limitatief gebruik') !== false):?>
                    Zie gebruiksvoorwaarden: <a target="_blank" href="<?php echo "/s/nl/page/gebruiksvoorwaarden#limitatief"; ?>">Limitatief gebruik</a>
                  <?php elseif(strpos($value->asHtml(), 'Limitative use') !== false):?>
                    See terms of use: <a target="_blank" href="<?php echo "/s/en/page/gebruiksvoorwaarden#limitatief"; ?>">Limitative use</a>
                  
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>
                <?php elseif($propertyData['property']->term() == 'dcterms:dateAccepted'):?>
                  <?php echo $value->asHtml();?>
                  <?php if(isset($values['dcterms:temporal']['values'])): ;?>
                 
                    <a target="_blank" href="<?php echo $values['dcterms:temporal']['values'][0]->asHtml();?>"><i class="fas fa-info-circle"></i></a>
                  <?php endif;?>                 
                <?php elseif($propertyData['alternate_label'] == 'Periode'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                   <?php echo $text[0]; ?>
                    <a target="_blank" href="<?php echo $text[1].$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>
                <?php elseif($propertyData['alternate_label'] == 'Onderwerp: wie'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                   <?php echo $text[0]; ?>
                    <a target="_blank" href="<?php echo $text[1].$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>   
                  <?php elseif($propertyData['alternate_label'] == 'Opschrift'):?>        
                    <?php if(strpos($value->asHtml(), 'rtf1') !== false):?>       
                      <?php $text = preg_replace('"{\*?\\\\.+(;})|\\s?\\\[A-Za-z0-9]+|\\s?{\\s?\\\[A-Za-z0-9‹]+\\s?|\\s?}\\s?"', '', $value->asHtml());?>                   
                      <?php $text = strip_tags($text);?>
                      <?php 
                      $plain = $value->asHtml();
                      // we have to remove all line breaks, otherwise
                      // the RTF>TXT regexp below doesn't work correctly.
                      $plain = preg_replace( '/\r|\n/', '', $plain);

                      // RTF>TXT (https://stackoverflow.com/a/42525858/357546)
                      $plain = preg_replace('"{\*?\\\\.+(;})|\\s?\\\[A-Za-z0-9]+|\\s?{\\s?\\\[A-Za-z0-9‹]+\\s?|\\s?}\\s?"', '', $plain);
                      // special characters; for a full list, see:
                      // https://www.oreilly.com/library/view/rtf-pocket-guide/9781449302047/ch04.html

                     
                      $plain = urldecode($plain);

                      $plain = str_replace("&#039;","",$plain);
                   
                      $plain = str_replace("\\3f", '?', $plain);
                      $plain = str_replace("\\80", '€', $plain);
                      $plain = str_replace("\\a8", '¨', $plain);
                      $plain = str_replace("\\ab", '«', $plain);
                      $plain = str_replace("\\ae", '®', $plain);
                      $plain = str_replace("\\b0", '°', $plain);
                      $plain = str_replace("\\bb", '»', $plain);
                      $plain = str_replace("\\c4", 'Ä', $plain);
                      $plain = str_replace("\\c9", 'É', $plain);
                      $plain = str_replace("\\d6", 'Ö', $plain);
                      $plain = str_replace("\\dc", 'Ü', $plain);
                      $plain = str_replace("\\df", 'ß', $plain);
                      $plain = str_replace("\\e0", 'à', $plain);
                      $plain = str_replace("\\e2", 'â', $plain);
                      $plain = str_replace("\\e4", 'ä', $plain);
                      $plain = str_replace("\\e7", 'ç', $plain);
                      $plain = str_replace("\\e8", 'è', $plain);
                      $plain = str_replace("\\e9", 'é', $plain);
                      $plain = str_replace("\\ea", 'ê', $plain);
                      $plain = str_replace("\\eb", 'ë', $plain);
                      $plain = str_replace("\\ee", 'î', $plain);
                      $plain = str_replace("\\f4", 'ô', $plain);
                      $plain = str_replace("\\f6", 'ö', $plain);
                      $plain = str_replace("\\f8", 'ø', $plain);
                      $plain = str_replace("\\fb", 'û', $plain);
                      $plain = str_replace("\\fc", 'ü', $plain);
                      $plain = str_replace("\\b0", '°', $plain);             
                      $plain = preg_replace('/^-0 /', '', $plain);
                      echo $plain;  
                      ?>
                    <?php else:?>
                    <?php echo  strip_tags($value); ?>
                    <?php endif;?>      
                    
                <?php elseif($propertyData['alternate_label'] == 'Verzamelaar'):?>
                  <?php 
                    $text = explode("$$",$value->asHtml());
                    echo '<a href="/s/nl/objecten?q=&filter[0][join]=and&filter[0][field]=abcd_fullName&filter_txt[0][type]=in&filter[0][value]='.$text[0].'">'.$text[0].'</a>';
                  ?>      
                <?php elseif($propertyData['alternate_label'] == 'Locatie'):?>
                  <?php echo $value->asHtml();?>
                  <?php if(isset($values['dwc:municipality']['values'])):?>                                         
                      <?php                       
                      $text = $values['dwc:municipality']['values'][0];
                      //check if municipality contains a url
                      if(str_contains($text,"http")):?>
                        <a target="_blank" href="<?= $text ?>"><i class="fas fa-info-circle"></i></a>
                      <?php else:  
                        //no url? check for geonames id in brackets
                        preg_match_all("/\\[(.*?)\\]/", $text, $matches); 
                        $id = $matches[1][1];
                        $id = explode("id:",$id);
                        $id = $id[1];?>                    
                        <a target="_blank" href="<?php echo 'https://www.geonames.org/'. $id; ?>"><i class="fas fa-info-circle"></i></a>
                      <?php endif;?>
                  <?php endif;?>  
                               
                <?php elseif($propertyData['alternate_label'] == 'Onderwerp: wat'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value->asHtml());?>
                   <?php echo $text[0]; ?>
                    <a target="_blank" href="<?php echo 'https://www.geonames.org/'.$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>    
                <?php elseif($propertyData['alternate_label'] == 'Wetenschappelijke naam'):?>
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>
                    <?php $text = explode('$$',$value.'');?>
                    <?php                    
                    $text[0] = str_replace("((","(",$text[0]);
                    $text[0] = str_replace("))",")",$text[0]);
                    $text[0] = str_replace("()","",$text[0]);
                    if(str_contains($text[0],"(")):
                      $name = explode("(",$text[0]);
                      $name[0] = "<span style='font-style:italic'>".$name[0]."</span>";
                      $only_name = $name[0];
                    else:  
                      $name = explode(",",$text[0]);
                      $name[0] = "<span style='font-style:italic'>".$name[0]."</span>";
                      $only_name = $name[0];
                    endif;  
                    
                    echo '<a href="'.$search_url.'?q=&filter[0][join]=and&filter[0][field]=dwc_scientificName_txt&filter[0][type]=in&filter[0][value]='.strip_tags($only_name).'">'.$text[0].'</a>';
                    ?>
                    <?php if($text[1]):?>
                      <?php $text[1] = html_entity_decode($text[1]); ?>
                      <a target="_blank" href="<?php echo strip_tags($text[1]); ?>"><i class="fas fa-info-circle"></i></a>
                    <?php endif;?>
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>           
                <?php elseif($propertyData['alternate_label'] == 'Objectnaam'):?>                     
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>                    
                    <?php $text = explode('$$',$value->asHtml());?>      
                    <?php if($text[0]):?>            
                      <a href="<?php echo $search_url.'?q=&facet['.$pre.'dcterms_alternative_ss][0]='.$text[0]; ?>"><?php echo $text[0]; ?></a>
                      <?php if(isset($text[2])):?> 
                        <?php $text[1] = str_replace("vocab.getty.edu/aat/","www.getty.edu/vow/AATFullDisplay?find=&amp;logic=AND&amp;note=&amp;subjectid=",$text[1]);?>      
                        <a target="_blank" href="<?php echo $text[1].$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                      <?php elseif($text[1]):?>   
                        <?php $text[1] = str_replace("vocab.getty.edu/aat/","www.getty.edu/vow/AATFullDisplay?find=&amp;logic=AND&amp;note=&amp;subjectid=",$text[1]);?>      
                        <a target="_blank" href="<?php echo $text[1]; ?>"><i class="fas fa-info-circle"></i></a>
                      <?php endif;?>
                    <?php endif;?>  
                  <?php else:?>
                    <a href="<?php echo $search_url.'?q=&facet['.$pre.'dcterms_alternative_ss][0]='.$value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>                  
                  <?php endif;?>       
                <?php elseif($propertyData['alternate_label'] == 'Verwervingsbron'):?>                
                  <?php $bron = explode("$$",$value->asHtml());?>
                  <a href="<?php echo $search_url.'?q=&filter[0][join]=and&filter[0][field]=abcd_acquisitionSourceText_txt&filter[0][type]=in&filter[0][value]='.$bron[0]; ?>"><?php echo $bron[0]; ?></a>                  
                  <?php if(!empty($bron[1])):?>
                    <a target="_blank" href="<?php echo $bron[1]; ?>"><i class="fas fa-info-circle"></i></a>                 
                  <?php endif;?>  
                <?php elseif($propertyData['alternate_label'] == 'Gerelateerde objecten'):?>
                  <?php 
                  $objecten = $value->asHtml();
                  $objecten = explode(";",$objecten);
                  $rel_arr = [];
                  foreach($objecten as $object):               
                    $query = 'property[0][joiner]=and&property[0][property]=10&property[0][type]=eq&property[0][text]='.$object.'&item_set_id[]=&site_id=';
                    parse_str($query,$query);
                    $rel = $items = $this->api()->searchOne('items',$query);
                    $rel = $rel->getContent();
                    if($rel):
                      $rel_arr[$rel->value('dcterms:title',array("lang" => $lang)).rand()] = '<div><a href="'.$rel->url().'">'.$rel->value('dcterms:title',array("lang" => $lang)).'</a></div>';
                    endif;
                  endforeach;
                  ksort($rel_arr);
                  foreach($rel_arr as $key=>$value):
                    echo $value;
                  endforeach;  
                  ?>  
                <?php elseif($propertyData['alternate_label'] == 'Vervaardiger'):?>                  
                  <?php if(strpos($value->asHtml(), '$$') !== false):?>                   
                    <?php 
                    $text = explode('$$',$value->asHtml());
                    if($text[1]):
                      $cre_r = array();$medval = "";
                      foreach($values['dcterms:creator']['values'] as $cre):
                        if(str_contains($text[0],$cre->asHtml())):
                        $medval = $cre->asHtml();
                        endif;
                      endforeach;
                      ?>
                      <?php if($medval):?>                    
                        <a href="<?php echo $search_url.'?q=&facet['.$pre.'dcterms_creator_ss][0]='.$medval; ?>"><?php echo $text[0]; ?></a>
                        <?php if(sizeof($text) == 3):?>
                          <a target="_blank" href="<?php echo $text[1].$text[2]; ?>"><i class="fas fa-info-circle"></i></a>
                        <?php elseif(sizeof($text) == 2  && $text[1]):?>
                          <a target="_blank" href="<?php echo $text[1]; ?>"><i class="fas fa-info-circle"></i></a>
                        <?php endif;?>  
                      <?php endif;?>  
                    <?php else:?>
                      <?php echo $text[0]; ?>
                    <?php endif;?>  
                  <?php else:?>
                    <?php echo $value->asHtml(); ?>
                  <?php endif;?>                  
                <?php elseif (strpos($value->asHtml(), 'http') !== false && strpos($value->asHtml(), 'uri-value-link') === false):?>
                  <a target="_blank" href="<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php else:?>
                  <?php echo $value->asHtml(); ?>
                <?php endif;?>
            </div>
            <?php $i++;?>
      <?php endforeach; ?>
      </div>
    </div>
  </div>
  <?php endif;?>
<?php endforeach; ?>
