<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$not = array('Title','Description','Is Version Of','Is Part Of','Language','Provenance');
$notalt = array('Collectie ID','Referenties object','Beeld','Beeld copyright');
?>

<?php foreach ($templateProperties as $term => $property): ?>
  <?php 
    if($property->isPrivate()):
      continue;
    endif;
    $propertyData = '';
    if(isset($values[$property->property()->term()])):
      $propertyData = $values[$property->property()->term()];
    else:
      continue;
    endif;
  ?>  
  <?php if(!in_array($propertyData['property']->label(),$not) && !in_array($propertyData['alternate_label'],$notalt)):?>
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <h4 class="title is-6" style="font-size:0.9rem;padding-top:0.3rem;padding-bottom:0.3rem;line-height: 1.6;">
      <?php if ($propertyData['alternate_label']): ?>
      <?php echo $escape($propertyData['alternate_label']); ?>
      <?php else: ?>
      <?php echo $escape($translate($propertyData['property']->label())); ?>
      <?php endif; ?>
      <?php if ('term' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
      <?php elseif ('vocab' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
      <?php endif; ?>
      </h4>
    </div>
    <div class="col-xs-12 col-md-8">
      <div class="values" style="font-size:0.9rem;padding-top:0.3rem;padding-bottom:0.3rem;line-height: 1.6;">
      <?php $i=0;?>
      <?php foreach ($propertyData['values'] as $value): ?>
          <?php
          $valueType = $value->type();
          $class = ['value'];
          if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
              $class[] = 'resource';
              $class[] = $escape($value->valueResource()->resourceName());
          } elseif ('uri' == $valueType) {
              $class[] = 'uri';
          }
          if (!$value->isPublic()) {
              $class[] = 'private';
          }
          ?>

            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>

                <?php if($propertyData['alternate_label'] == 'Thema'):?>
                  <a target="_blank" href="/nl/item-set?fulltext_search=&property[0][joiner]=and&property[0][property]=8&property[0][type]=eq&property[0][text]=<?php echo $value->asHtml(); ?>&resource_class_id[]=&resource_template_id[]=&submit=Zoeken"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['alternate_label'] == 'Department/Research/Group/Unit'):?>                  
                  <a href="<?php echo '/herkul/s/en/find?q=&facet[schema:subOrganization][0]='.$value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                 <?php elseif($propertyData['alternate_label'] == 'Faculty'):?>                  
                  <a href="<?php echo '/herkul/s/en/find?q=&facet[schema:parentOrganization][0]='.$value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['alternate_label'] == 'Research keywords'):?>                  
                  <a href="<?php echo '/herkul/s/en/find?q=&facet[schema:keywords][0]='.$value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php else:?>
                  <?php echo $value->asHtml(); ?>
                <?php endif;?>
            </div>
            <?php $i++;?>
      <?php endforeach; ?>
      </div>
    </div>
  </div>
  <?php endif;?>
<?php endforeach; ?>
