<section class="section text-columns">
  <div class="container">
    <?php if($block->dataValue('title')):?>
      <h3 class="title is-3"><?php echo $block->dataValue('title');?></h3>
    <?php endif;?>
    <?php if($block->dataValue('title1') && $block->dataValue('title2') && !$block->dataValue('title3')):?>
      <?php $layout = "is-".$block->dataValue('layout');?>
    <?php else:?>
      <?php $layout = "";?>
    <?php endif;?>
    <div class="columns">
      <?php for($i = 1; $i <= 3; $i++){ ?>
        <?php if($block->dataValue('title'.$i)):?>
          <?php if($i == 1):?>
            <div class="column is-6">
          <?php else:?>
            <div class="column is-6">
          <?php endif;?>
          <div class="box equal-height box-<?php echo $i;?>">
            <div class="media-content">
              <div class="content">
                <h2 class="is-3 title">
                        <?php echo $block->dataValue('title'.$i);?>
                </h2>
                <?php echo $block->dataValue('text'.$i);?>
                <?php if($block->dataValue('link'.$i) && $block->dataValue('linktext'.$i)):?>
                    <a class="card-footer-item" href="<?php echo $block->dataValue('link'.$i);?>">
                    <?php echo $block->dataValue('linktext'.$i);?></a>
                <?php endif;?>
              </div>
            </div>
          </div>
        </div>
        <?php endif;?>
      <?php } ?>
    </div>
  </div>
</section>
